name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Inject Firebase Test Token
        run: echo $FIREBASE_TEST_TOKEN > ./app/google-services.json
      - name: Build the app
        run: ./gradlew build